#! /usr/bin/env python3

import sys, os
from pathlib import Path
import subprocess as sp

prev_cwd = Path.cwd();
script_dir = Path(__file__).resolve().parent
os.chdir(script_dir)

sp.check_call(["cargo", "build", "--bin", "interpreter"])
os.chdir(prev_cwd)

bin_path = script_dir / "target/debug/interpreter"
try:
    sp.check_call([bin_path, *sys.argv[1:]], text=True)
except KeyboardInterrupt:
    pass
except sp.CalledProcessError as e:
    print(f"Exited with status {e.returncode}")
    exit(e.returncode)


