[package]
name = "emu-lib"
version = "0.1.0"
authors = ["Elliot Lockerman <elliot@lockerman.info>"]
edition = "2021"

[dependencies]
common = { path = "../common" }
log = "0.4.22"
num-derive = "0.4.2"
num-traits = "0.2.14"

