[package]
name = "as-cli"
version = "0.1.0"
authors = ["Elliot Lockerman <elliot@lockerman.info>"]
edition = "2021"

[dependencies]
as-lib = { path = "../as-lib" }
clap = { version = "4.5.8", features = ["derive"] }
env_logger = "0.11.5"
