[package]
name = "common"
version = "0.1.0"
authors = ["Elliot Lockerman <elliot@lockerman.info>"]
edition = "2021"

[dependencies]
derive_more = "0.99.18"
num-derive = "0.4.2"
num-traits = "0.2.14"

