[package]
name = "disassembler"
version = "0.1.0"
authors = ["Elliot Lockerman <elliot@lockerman.info>"]
edition = "2021"

[dependencies]
clap = { version = "4.5.13", features = ["derive"] }
common = { path = "../common" }
aout = { path = "../aout" }
env_logger = "0.11.5"
log = "0.4.22"

